on: ["push", "pull_request"]

name: Test Codecov

jobs:

  test-coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: npm install, generate coverage report
      run: |
        npm ci
        npm run test-cov

    - name: Send coverage report to codecov for visualization
      uses: codecov/codecov-action@v3
      with:
        verbose: true
